version: '3'
services: 
  web:
    build: .
    ports: 
      - "5000:5000"
    depends_on: 
      - redis
      - db
    # volumes:
    #   - .:/go/src/github.com/rubixq/rubixcore
  redis:
    image: redis
  db:
    image: mongo

