version: '3'
services: 
  web:
    build: .
    ports: 
      - 5000:5000
    depends_on: 
      - redis
      - db
    # volumes:
    #   - .:/go/src/github.com/rubixq/rubixcore
  redis:
    image: redis
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: rub1xc0r3
  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080

